from enum import Enum

class EventType(str, Enum):
    # Data Sync Events
    WORKITEM_SYNCED = "WORKITEM_SYNCED"
    WORKITEM_UPDATED = "WORKITEM_UPDATED"
    
    # Workflow Detection Events
    STALL_DETECTED = "STALL_DETECTED"
    SLA_AT_RISK = "SLA_AT_RISK"
    EXCEPTION_CREATED = "EXCEPTION_CREATED"
    
    # Action Lifecycle Events
    ACTION_DRAFT_CREATED = "ACTION_DRAFT_CREATED"
    ACTION_APPROVED = "ACTION_APPROVED"
    ACTION_REJECTED = "ACTION_REJECTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_FAILED = "ACTION_FAILED"
    
    # Scheduled/Periodic Events
    WEEKLY_REPORT_GENERATED = "WEEKLY_REPORT_GENERATED"
    MEETING_TASKS_EXTRACTED = "MEETING_TASKS_EXTRACTED"
