from enum import Enum

# 1. Ingestion & Normalization
class IngestionState(str, Enum):
    FETCHING = "FETCHING"
    NORMALIZING = "NORMALIZING"
    HASHING = "HASHING"
    UPSERTING = "UPSERTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

# 2. Stall Detection & Nudge
class StallDetectionState(str, Enum):
    CHECKING_POLICIES = "CHECKING_POLICIES"
    DETECTED_STALL = "DETECTED_STALL"
    CHECKING_COOLDOWN = "CHECKING_COOLDOWN"
    DRAFTING_NUDGE = "DRAFTING_NUDGE"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    AUTO_SENDING = "AUTO_SENDING"
    SENT = "SENT"
    SKIPPED = "SKIPPED"

# 3. SLA Monitor & Escalation
class SLAMonitorState(str, Enum):
    CALCULATING_HEADROOM = "CALCULATING_HEADROOM"
    RISK_DETECTED = "RISK_DETECTED"
    ESCALATING = "ESCALATING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    NOTIFYING_MANAGER = "NOTIFYING_MANAGER"
    RESOLVED = "RESOLVED"

# 4. Weekly Report Generator
class ReportGeneratorState(str, Enum):
    AGGREGATING_STATS = "AGGREGATING_STATS"
    SUMMARIZING_COMPLETED = "SUMMARIZING_COMPLETED"
    IDENTIFYING_BLOCKERS = "IDENTIFYING_BLOCKERS"
    DRAFTING_REPORT = "DRAFTING_REPORT"
    PUBLISHING = "PUBLISHING"

# 5. Meeting Task Extraction
class MeetingExtractionState(str, Enum):
    PROCESSING_NOTES = "PROCESSING_NOTES"
    EXTRACTING_ITEMS = "EXTRACTING_ITEMS"
    VALIDATING_SCHEMA = "VALIDATING_SCHEMA"
    CREATING_DRAFTS = "CREATING_DRAFTS"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
